server:
  port: 8002
  servlet.context-path: /business

  # 数据库连接
spring:
  datasource:
    url: jdbc:mysql://120.26.29.90/train_business?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_business
    password: train
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

# mybatis xml路径
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com.fanxin.train.business.mapper: trace
