server:
  port: 8000

spring:
  cloud:
    gateway:
      routes[0]:
        id: member
        uri: http://127.0.0.1:8001
        predicates[0]: Path=/member/**
      routes[1]:
        id: business
        uri: http://127.0.0.1:8002
        predicates[0]: Path=/business/**
      globalcors:
        cors-configurations:
          '[/**]':
            # 允许请求来源
            allowedOriginPatterns: "*"
            # 允许携带的头信息
            allowedHeaders: "*"
            # 允许的请求方式
            allowedMethods: "*"
            # 是否允许携带cookie
            allowCredentials: true
            # 跨域检测的有效期，会发起一个OPTION请求
            maxAge: 3600