server:
  port: 8003
  servlet:
    context-path: /batch
spring:
  datasource:
    # 数据库连接
    url: jdbc:mysql://120.26.29.90:3306/train_batch?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: train_batch
    password: train
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  # mybatis xml路径
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com:
      fanxin:
        train:
          batch:
            mapper: trace